version: '3.9'

services:
  postgres:
    image: postgres:13
    container_name: tresdoce-test-utils-global-postgres
    restart: always
    ports:
      - '5432:5432'
    environment:
      TZ: 'America/Argentina/Buenos_Aires'
      POSTGRES_DB: my_db
      POSTGRES_USER: root
      POSTGRES_PASSWORD: 123456

  mysql:
    image: mysql:5.7
    container_name: tresdoce-test-utils-global-mysql
    restart: always
    ports:
      - '3306:3306'
    environment:
      TZ: 'America/Argentina/Buenos_Aires'
      MYSQL_ROOT_PASSWORD: 123456
      MYSQL_DATABASE: my_db
      MYSQL_PASSWORD: 123456
      #MYSQL_USER: root

  mongo:
    image: mongo:5.0
    container_name: tresdoce-test-utils-global-mongo
    restart: always
    ports:
      - '27017:27017'
    environment:
      TZ: 'America/Argentina/Buenos_Aires'
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: 123456
      MONGO_INITDB_DATABASE: test_db

  redis:
    image: redis:6.2-alpine
    container_name: tresdoce-test-utils-global-redis
    restart: always
    ports:
      - '6379:6379'
    environment:
      TZ: 'America/Argentina/Buenos_Aires'
      REDIS_PORT: 6379
      REDIS_PASSWORD: 123456
      REDIS_HOST: cache
      #REDIS_USERNAME: default
    command: [ "redis-server", "--appendonly", "yes", "--requirepass","123456" ]

  dynamodb:
    image: amazon/dynamodb-local:latest
    container_name: tresdoce-test-utils-global-dynamodb
    restart: always
    ports:
      - '8000:8000'
    environment:
      TZ: 'America/Argentina/Buenos_Aires'
      AWS_ACCESS_KEY_ID: local
      AWS_SECRET_ACCESS_KEY: local
      AWS_REGION: us-east-1

  elasticsearch:
    image: docker.elastic.co/elasticsearch/elasticsearch:8.13.4
    container_name: tresdoce-test-utils-global-elasticsearch
    restart: always
    ports:
      - '9200:9200'
    environment:
      - TZ=America/Argentina/Buenos_Aires
      - discovery.type=single-node
      - node.name=elasticsearch
      - ES_JAVA_OPTS=-Xms1g -Xmx1g
      - xpack.security.enabled=false

  jaeger:
    image: jaegertracing/all-in-one:latest
    container_name: tresdoce-test-utils-global-jaeger
    restart: always
    ports:
      - '6831:6831/udp'
      - '6832:6832/udp'
      - '5778:5778'
      - '16686:16686'
      - '4317:4317'
      - '4318:4318'
      - '14250:14250'
      - '14268:14268'
      - '14269:14269'
      - '9411:9411'
    environment:
      TZ: 'America/Argentina/Buenos_Aires'
      COLLECTOR_OTLP_ENABLED: 'true'

  authorizer:
    image: lakhansamani/authorizer:latest
    container_name: tresdoce-test-utils-global-authorizer
    restart: always
    ports:
      - '3001:3001'
    environment:
      ENV: 'development'
      ADMIN_SECRET: 'admin'
      PORT: 3001
      DATABASE_TYPE: postgres
      DATABASE_URL: postgres://root:123456@postgres:5432/my_db
      REDIS_URL: redis://:123456@redis:6379
      CUSTOM_ACCESS_TOKEN_SCRIPT: function(user,tokenPayload){var data=tokenPayload;data.user=user;return data;}
      DISABLE_PLAYGROUND: false
      DISABLE_EMAIL_VERIFICATION: false
      DISABLE_MAGIC_LINK_LOGIN: true
      ROLES: user,admin,super_admin
      DEFAULT_ROLES: user
      PROTECTED_ROLES: admin,super_admin
      #SMTP_HOST: smtp.resend.com
      #SMTP_PORT: 465
      #SMTP_USERNAME: resend
      #SMTP_PASSWORD: RESENDE_TOKEN
      #SENDER_EMAIL: onboarding@resend.dev
      SMTP_HOST: smtp.sendgrid.net
      SMTP_PORT: 587
      SMTP_USERNAME: apikey
      SMTP_PASSWORD: SEND_GRID_TOKEN
      SENDER_EMAIL: mdelgado@tresdoce.com.ar
      SENDER_NAME: Test Authorizer (Resend)
    depends_on:
      - postgres
      - redis

  keycloak:
    image: quay.io/keycloak/keycloak:25.0.2
    container_name: tresdoce-test-utils-global-keycloak
    restart: always
    ports:
      - '8443:8443'
    environment:
      KC_DB: postgres
      KC_DB_URL: jdbc:postgresql://postgres:5432/my_db
      KC_DB_USERNAME: root
      KC_DB_PASSWORD: 123456
      KC_HOSTNAME: localhost
      KC_HOSTNAME_PORT: 8443
      KC_HOSTNAME_STRICT_BACKCHANNEL: true
      KC_HOSTNAME_STRICT: false
      KC_HOSTNAME_STRICT_HTTPS: false
      KC_LOG_LEVEL: info
      KC_METRICS_ENABLED: true
      KC_HEALTH_ENABLED: true
      KEYCLOAK_ADMIN: admin
      KEYCLOAK_ADMIN_PASSWORD: admin
    healthcheck:
      test: [ "CMD", "curl", "-f", "http://localhost:8443/health/ready" ]
      interval: 15s
      timeout: 2s
      retries: 15
    command: start-dev --http-port=8443
    depends_on:
      - postgres




