export const DYNAMOOSE_OPTIONS = Symbol('DYNAMOOSE_OPTIONS');
export const DYNAMOOSE_MODULE_OPTIONS = Symbol('DYNAMOOSE_MODULE_OPTIONS');
export const DYNAMOOSE_INITIALIZATION = Symbol('DYNAMOOSE_INITIALIZATION');
